#!/bin/sh
# Restore a backup of the game world.
set -eux

SOURCE_DIRECTORY=${SOURCE_DIRECTORY:-server}
BACKUPS_DIRECTORY=${BACKUPS_DIRECTORY:-backups}
BACKUP_WORLD_NAME=${BACKUP_WORLD_NAME:-world}
BACKUP_WORLD_DATE=${BACKUP_WORLD_DATE:-`date '+%m%d%Y'`}

unzip ${BACKUPS_DIRECTORY}/${SOURCE_DIRECTORY}-${BACKUP_WORLD_NAME}.world.${BACKUP_WORLD_DATE}
exit $?
